#!/usr/bin/env node
// Synthetic happy-path fixtures for each FHIR R4 resource this server exposes.
// Each fixture is generated by the same mapper the route handlers use, then
// POSTed to the public HAPI validator at https://validator.fhir.org/validate.
//
// Usage: node scripts/validate-fhir-fixtures.mjs
// Exits 0 on success, 1 if the validator returns any `error` issue.

import { staffToFhirPractitioner } from "../lib/fhir/practitioner";
import { encounterRowToFhir } from "../lib/fhir/encounter";
import { appointmentRowToFhir } from "../lib/fhir/appointment";
import { checkInRowToObservation } from "../lib/fhir/observation";
import { intakeRowToCoverage } from "../lib/fhir/coverage";
import { documentRowToFhir } from "../lib/fhir/documentReference";

const BASE = "https://ehr.example.test/api/fhir/R4";
const PATIENT_ID = "11111111-1111-4111-8111-111111111111";
const PRACTITIONER_ID = "22222222-2222-4222-8222-222222222222";
const ENCOUNTER_ID = "33333333-3333-4333-8333-333333333333";
const APPT_ID = "44444444-4444-4444-8444-444444444444";

const fixtures = {
  Practitioner: staffToFhirPractitioner(
    {
      id: PRACTITIONER_ID,
      first_name: "Jamie",
      last_name: "Rivera",
      email: "jamie.rivera@example.test",
      phone: "555-0100",
      provider_npi: "1234567893",
      is_active: true,
      job_title: "Licensed Clinical Social Worker",
      updated_at: "2026-05-20T12:00:00Z",
    },
    {
      staff_id: PRACTITIONER_ID,
      provider_npi: "1234567893",
      specialty: "Behavioral Health",
      credentials: "LCSW",
      license_number: "LCSW-9001",
      license_state: "CA",
    },
  ),
  Encounter: encounterRowToFhir(
    {
      id: ENCOUNTER_ID,
      client_id: PATIENT_ID,
      provider_id: PRACTITIONER_ID,
      appointment_id: APPT_ID,
      encounter_status: "completed",
      started_at: "2026-05-19T15:00:00Z",
      ended_at: "2026-05-19T15:50:00Z",
      service_date: "2026-05-19",
      session_summary: "Routine therapy session, mood stable.",
      updated_at: "2026-05-19T16:00:00Z",
    },
    BASE,
  ),
  Observation: checkInRowToObservation(
    {
      id: "55555555-5555-4555-8555-555555555555",
      client_id: PATIENT_ID,
      encounter_id: ENCOUNTER_ID,
      status: "submitted",
      current_mood: "Anxious but managing",
      current_stressors: "Work deadlines",
      safety_concerns: "None",
      psychosocial_updates: "Started new exercise routine",
      patient_statement: "Feeling better than last week.",
      submitted_at: "2026-05-19T14:55:00Z",
      created_at: "2026-05-19T14:50:00Z",
      updated_at: "2026-05-19T14:55:00Z",
    },
    BASE,
  ),
  Appointment: appointmentRowToFhir(
    {
      id: APPT_ID,
      client_id: PATIENT_ID,
      provider_id: PRACTITIONER_ID,
      scheduled_start_at: "2026-05-19T15:00:00Z",
      scheduled_end_at: "2026-05-19T15:50:00Z",
      appointment_status: "completed",
      appointment_type: "Individual therapy",
      reason: "Follow-up session",
      cancellation_reason: null,
      updated_at: "2026-05-19T16:00:00Z",
    },
    BASE,
  ),
  Coverage: intakeRowToCoverage(
    {
      id: "66666666-6666-4666-8666-666666666666",
      client_id: PATIENT_ID,
      status: "submitted",
      insurance: {
        payerName: "Blue Cross Blue Shield",
        memberId: "BCBS-ABC-12345",
        planName: "PPO Gold",
        relationship: "self",
        effectiveDate: "2026-01-01",
      },
      submitted_at: "2026-04-15T10:00:00Z",
      created_at: "2026-04-15T10:00:00Z",
    },
    BASE,
  ),
  DocumentReference: documentRowToFhir(
    {
      id: "77777777-7777-4777-8777-777777777777",
      client_id: PATIENT_ID,
      encounter_id: ENCOUNTER_ID,
      document_scope: "client",
      document_type: "intake_form",
      title: "Signed intake packet",
      file_name: "intake-packet.pdf",
      storage_bucket: "client-documents",
      storage_path: `clients/${PATIENT_ID}/intake-packet.pdf`,
      mime_type: "application/pdf",
      file_size_bytes: 123456,
      notes: "Patient initial intake packet, all consents signed.",
      created_at: "2026-04-15T10:05:00Z",
      updated_at: "2026-04-15T10:05:00Z",
    },
    BASE,
  ),
};

async function validate(resourceType: string, resource: unknown) {
  const res = await fetch(`https://hapi.fhir.org/baseR4/${resourceType}/$validate`, {
    method: "POST",
    headers: { "Content-Type": "application/fhir+json", accept: "application/fhir+json" },
    body: JSON.stringify(resource),
  });
  const outcome = await res.json().catch(() => null);
  if (!res.ok || !outcome) {
    return { resourceType, ok: false, status: res.status, errors: [{ diagnostics: `HTTP ${res.status}` }], warnings: [] };
  }
  type Issue = { severity?: string; diagnostics?: string };
  const issues: Issue[] = Array.isArray(outcome?.issue) ? outcome.issue : [];
  const errors = issues.filter((i) => i.severity === "error" || i.severity === "fatal");
  return {
    resourceType,
    ok: errors.length === 0,
    errors,
    warnings: issues.filter((i: Issue) => i.severity === "warning"),
  };
}

async function main() {
const results = [];
for (const [type, resource] of Object.entries(fixtures)) {
  try {
    const r = await validate(type, resource);
    results.push(r);
    const tag = r.ok ? "PASS" : "FAIL";
    console.log(
      `[${tag}] ${type}  warnings=${r.warnings?.length ?? 0} errors=${r.errors?.length ?? 0}`,
    );
    if (!r.ok) {
      for (const e of r.errors ?? []) {
        console.log("   -", e.diagnostics ?? JSON.stringify(e));
      }
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.log(`[ERROR] ${type}`, msg);
    results.push({ resourceType: type, ok: false, errors: [{ diagnostics: msg }], warnings: [] });
  }
}

const failed = results.filter((r) => !r.ok);
if (failed.length) {
  console.log(`\n${failed.length} resource(s) failed HAPI validation.`);
  process.exit(1);
}
console.log("\nAll resources passed HAPI validation.");

}
main().catch((e) => { console.error(e); process.exit(1); });
